Traceback (most recent call last):
  File "test/verify/machineslib.py", line *, in testCreate
    start_vm=True, delete=False))
  File "test/verify/machineslib.py", line *, in createDownloadAnOSTest
    dialog.open() \
*
subprocess.CalledProcessError: Command 'ps aux * returned non-zero exit status 1.
