warning: Unexpected error when getting logged in accounts*
*
Traceback (most recent call last):
  File "test/verify/check-users", line *, in testUserPasswords
    b.wait_visible("#account-groups-helper")
*
testlib.Error: timeout
